### ISSUE TITLE
Bug: Solution filters do not work with Japanese sentences

### ISSUE THREAD

**Issue by stochaztic** [blmage/duolingo-solution-viewer#141]
When viewing solutions for a Japanese sentence, attempting to add a "Present" filter whatsoever always results in no hits, regardless of word-position mode. (I have not checked Chinese to see if it exhibits the same behavior, but this seems likely.)

Obviously Japanese characters present a challenge to the filter feature, especially given the difficulty in determining the concept of a "word" with the Japanese data in the first place. But any functionality would be a great benefit, as due to the way the Japanese course is programmed, solution sets of hundreds or thousands of results are common. Having a working filter would be extremely helpful.

Additionally, a cursory glance at the code for the filter functionality shows it currently intentionally prevents filter items of length 1; having length-1 filters would be useful, however, for Japanese and similar languages.

**Comment by blmage** [comment]
Thank you very much for reporting this problem! (not sure why it has remained unnoticed until now)

After a quick glance at the first Japanese lesson, it seems that the assumption that we make that each vertex in the solution graphs corresponds to one word does not hold for the Japanese course, for which each vertex corresponds to only one "letter".

This not only breaks the filter (because we end up with only "words" of length 1), but also almost everything related to matching on similarity (when it's based on bigrams).

Not sure how to fix this though, so I'll probably just start by disabling all these features for Japanese solutions.

If you have any idea, I'm opened to suggestions and/or contributions!

**Comment by stochaztic** [comment]
Thanks for checking it out. For the time being, would it be possible to just do a simple "if a final sentence string contains this string anywhere" type filter for the Japanese sentences? As mentioned, with result sets in the thousands, even just such a basic filter would be a huge help. Similarity matching and such would be nice someday, but just a simple contains filter would handle 99% of my needs.

Thanks for looking into this!

**Comment by stochaztic** [comment]
Here's an [example sentence on the forum](https://forum.duolingo.com/comment/34310005) with 624 solutions, so for example, being able to put in "祈り" or even  just "祈" in the filter and narrow it down to a more reasonable number to manually look through would be great.

**Comment by blmage** [comment]
Filtering on Japanese solutions has been fixed in version `4.3.0`.

Let me know if there is anything else that could be improved!
