### ISSUE TITLE
Random umlaut appears in solutions

### ISSUE THREAD

**Issue by PineappleSnackz** [blmage/duolingo-solution-viewer#182]
So far I've only experienced this issue when the solution contains "Eure". It corrects my answer with "Eüre" even though the official solutions do not use "Eüre".
![msedge_yX7LDEyZwI](https://user-images.githubusercontent.com/47675689/176957718-37572e91-0494-43e6-a9ca-39c3eefec0b5.png)
![msedge_3hgDVxzmJD](https://user-images.githubusercontent.com/47675689/176957720-4c94e06b-a0a4-4664-b1f8-00bb3a696635.png)
*Solution on discussions page*
![msedge_NJqQLtD7bJ](https://user-images.githubusercontent.com/47675689/176957719-8cb8f262-2584-494c-828c-78361da88d64.png)

**Comment by blmage** [comment]
Thanks for reporting this issue!

This is probably another case of Duolingo trying to account for possible "tolerable" mistakes - here by automatically adding `eüre` as a variant of `eure` to the list of accepted solutions.

The main problem in this specific  case is that because `eure` looks like a simplified version of `eüre`, the extension only keeps the latter.

Fortunately, it seems that no `euere` variant of `eüre` is further added to the solution (whereas we have `schön` and `schoen`), so we can probably use this fact to detect and ignore variants that contain unwanted umlauts. 

In the meantime, I will try to improve the readability of the German solutions (I had not tested this course before!), because it seems that they contain a lof of noise (anytime eszetts or umlauts are involved at least).

**Comment by blmage** [comment]
Sorry for the delay!

The fix is ready, but I'm worried that the cleaning up of solutions is starting to have too much of an impact performance-wise (especially on larger lists), so I'm still looking for an alternative.

I'll keep you updated - hopefully it won't be too long.

**Comment by blmage** [comment]
Closing this as the fix was released [some time ago](https://github.com/blmage/duolingo-solution-viewer/commit/8fbd4f4ec99de979d369d53679742e8ea3e0dcc1).
